from dataclasses import dataclass
from typing import Any


@dataclass
class Finding:
    """
    Represents a security finding generated by the Analysis Engine.
    """

    title: str
    severity: str
    mitre_id: str
    description: str
    recommendation: str
    evidence: dict[str, Any]
    related_alerts: list